export const sample_foods=[
{
    id:'1',
    name:'Raw Banana Powder',
    price: 260,
    favorite:false,
    origins:['Kerala'],
    cookTime: '10-20',
    stars:4.5,
    imageUrl:'food-1.jpg',
    tags:['Banana Items'],
},
{
    id:'2',
    name:'Banana Chips',
    price: 100,
    favorite:true,
    origins:['Kerala','trivandrum'],
    stars:5,
    imageUrl:'food-2.jpg',
    tags:['Banana Items'],
},
{
    id:'3',
    name:'Banana Stem Juice',
    price: 150,
    favorite:true,
    origins:['Kerala','kaddakal'],
    stars:4.5,
    imageUrl:'food-3.jpg',
    tags:['Banana Items'],
},
{
    id:'4',
    name:'Raw Jackfruit Powder',
    price: 120,
    favorite:false,
    origins:['Kerala','trivandrum'],
    stars:4.5,
    imageUrl:'food-4.jpg',
    tags:['Jackfruit Items'],
},
{
    id:'5',
    name:'Raw Jackfruit Dry',
    price: 180,
    favorite:false,
    origins:['Kerala','trivandrum'],
    stars:4.5,
    imageUrl:'food-5.jpg',
    tags:['Jackfruit Items'],
},
{
    id:'6',
    name:'Jackfruit chips',
    price: 150,
    favorite:false,
    origins:['Kerala'],
    stars:4.5,
    imageUrl:'food-6.jpg',
    tags:['Jackfruit Items'],
},
{
    id:'7',
    name:'Black Pepper',
    price: 120,
    favorite:false,
    origins:['Kerala','waynad'],
    stars:4.5,
    imageUrl:'food-7.jpg',
    tags:['Peppers'],
},
{
    id:'8',
    name:'White Pepper',
    price: 130,
    favorite:false,
    origins:['Kerala','trivandrum'],
    stars:4.5,
    imageUrl:'food-8.jpg',
    tags:['Peppers'],
},
{
    id:'9',
    name:'Malli Kaapi',
    price: 200,
    favorite:false,
    origins:['Kerala','kochi'],
    stars:4.5,
    imageUrl:'food-10.jpg',
    tags:['Kaapi'],
},
];
export const sample_tags=[
    {name:"All",count:9},
    {name:"Banana",count:3},
    {name:'Pepper',count:2},
    {name:'Kaapi',count:1},
    {name:'Jackfruit',count:3},
];