export const sample_foods=[
    {
        id: '1',
        name:'Banana Powder',
        cookTime:'10-20',
        price:10,
        favorite: false,
        origins: ['Kerala'],
        stars:4.5,
        imageUrl:'food-1.jpg',
        tags:['Powder','Banana','Snack'],
    },
    {
        id: '2',
        name:'Raw Jackfruit Powder',
        cookTime:'20-30',
        price:20,
        favorite: true,
        origins: ['Kerala'],
        stars:4.5,
        imageUrl:'food-2.jpg',
        tags:['Powder','Jackfruit','Snack'],
    },
    {
        id: '3',
        name:'Coffee Powder',
        cookTime:'30-40',
        price:30,
        favorite: true,
        origins: ['Kerala'],
        stars:4.5,
        imageUrl:'food-3.jpg',
        tags:['Powder','Coffee','Snack'],
    },
    {
        id: '4',
        name:'Malli Powder',
        cookTime:'10-20',
        price:50,
        favorite: false,
        origins: ['Kerala'],
        stars:4.5,
        imageUrl:'food-4.jpg',
        tags:['Powder','Malli','Snack'],
    },
    {
        id: '5',
        name:'Pepper Powder',
        cookTime:'10-20',
        price:30,
        favorite: false,
        origins: ['Kerala'],
        stars:5,
        imageUrl:'food-5.jpg',
        tags:['Powder','Pepper','Snack'],
    },
];

export const sample_tags=[
    {name: 'All', count: 5},
    {name: 'Powder', count: 5},
    {name: 'Banana', count: 1},
    {name: 'Jackfruit', count: 1},
    {name: 'Coffee', count: 1},
    {name: 'Malli', count: 1},
    {name: 'Pepper', count: 1},
    {name: 'Snack', count: 5},
];

export const sample_users=[
    {
        id: 1,
        name: 'John Doe',
        email: 'john@gmail.com',
        password: '12345',
        address: 'Kerala',
        isAdmin: false,
    },
    {
        id: 2,
        name: 'Jane Doe',
        email: 'jane@gmail.com',
        password: '12345',
        address: 'Kerala',
        isAdmin: true,
    },
];